### ISSUE TITLE
Universal viewer attempts to load on browse pages

### ISSUE THREAD

**Issue by graykr** [UIUCLibrary/Digital-Exhibits-Issues-Features#12]
When I click "see all items with this value" (from the Metadata Browse module), I get an error "unable to load manifest." Scrolling down I see a black box, so I am thinking this indicates that universal viewer is attempting to load but can't find a IIIF manifest to do so successfully.

This is likely related to issue #8 

For example: https://exhibits.library.illinois.edu/s/ihlc-oral-histories/item/29419

Then click "view all items with this value" for the interviewer name, Dana Miller. Omeka takes you to this page:
https://exhibits.library.illinois.edu/s/ihlc-oral-histories/item?Search=&property%5B0%5D%5Bproperty%5D=6&property%5B0%5D%5Btype%5D=eq&property%5B0%5D%5Btext%5D=Dana%20Miller

![image](https://github.com/UIUCLibrary/Digital-Exhibits-Issues-Features/assets/9000176/d8ce3ca4-3268-4312-b4a3-7fae3ac0b02a)

**Comment by alexdryden** [comment]
@graykr this should be fixed by https://github.com/UIUCLibrary/Omeka-S-module-UniversalViewer/pull/1/, which will allow you to select "None" in the options for which version of UV to use in the Site Admin options.
