### ISSUE TITLE
Browse preview display does not correctly decode html entities

### ISSUE THREAD

**Issue by graykr** [UIUCLibrary/Digital-Exhibits-Issues-Features#6]
Apostrophes appear as &#039 in the browse preview block but normally on the item browse page (and the item page).

Browse block on regular page
![image](https://github.com/UIUCLibrary/Digital-Exhibits-Issues-Features/assets/9000176/9b5f4ebd-2f54-4421-a36b-d367cda85b04)

Browse item page
![image](https://github.com/UIUCLibrary/Digital-Exhibits-Issues-Features/assets/9000176/7f8c7368-e170-444b-955c-1115163c4ff1)

**Comment by alexdryden** [comment]
Fixed at 1.0.6
