### ISSUE TITLE
Legacy Media Viewer Appearing at Bottom of Item Pages

### ISSUE THREAD

**Issue by spenserbailey** [UIUCLibrary/Digital-Exhibits-Issues-Features#8]
This issue doesn't appear in the Sandbox sites that Krista built, because (I think) Alex said that the Sandbox has some modification that disables this.  However, since it does appear in the actual Omeka S site, I wanted to make sure it was noted here.  

The Universal Viewer appears at the bottom of item pages, and is redundant with the linked MediaSpace entries and the embedded transcripts.

**Comment by alexdryden** [comment]
This is fixed by https://github.com/UIUCLibrary/Omeka-S-module-UniversalViewer/pull/1/. You should be able to select "None" in the Site Admin Options under Player (near the bottom).
